---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/boundlr9/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp /css -a *  $DEPLOYPATH
    - /bin/cp /js -a *  $DEPLOYPATH
    - /bin/cp /img -a *  $DEPLOYPATH
    - /bin/cp /fonts -a *  $DEPLOYPATH
    

